### ISSUE TITLE
Maintenance thread failing with stabilization calls.

### ISSUE THREAD

**Issue by uzillion** [ecs251-w19-ucdavis/tacOS#14]
The maintenance thread is trying to call the worker's functions directly via its object, and is failing for some unclear reason even though it doesn't seem to use the requester's connection details anytime.

**Desirable Solution**
It would be ideal for maintenance to make calls without RPC. You could follow through the flow of the requests/program and see where and why exactly is the worker thread failing even though it doesn't seem to use the requester's connection details. Once found, you could place a conditional logic of some sort.

**Quick Fix (undesirable)**
Could make slight modifications to maintenance thread to send RPCs instead of object calls to stabilize the nodes. The maintenance thread will connect to the node just like any other client and make the RPC call in the defined way.

**Comment by aaronistheman** [comment]
Fixed. State class now has a flag "in_ring" specifying whether or not the node is in a ring (whether due to creating the ring or joining it); the maintenance thread does nothing unless this flag is set.
