### ISSUE TITLE
Possible permission denied errors inside docker containers for executables

### ISSUE THREAD

**Issue by uzillion** [ecs251-w19-ucdavis/tacOS#15]
Scripts inside the container give permission denied errors for some users inside the container.

**Comment by aaronistheman** [comment]
Should be able to fix this if there's a way in the Docker configuration file to do `chmod +x taco.py` during startup.

**Comment by uzillion** [comment]
> 
> 
> Should be able to fix this if there's a way in the Docker configuration file to do `chmod +x taco.py` during startup.

Yes, I assigned this to myself so that I don't forget. I'll take care of it, it's a minor issue.
